[package]
name = "formatter"
version = "0.1.0"
edition = "2021"

[dependencies]
itertools = "0.11"
miette = { version = "5.9", features = ["fancy"] }
wca = { version = "0.1", git = "https://github.com/Wandalen/wTools.git", branch = "alpha" }
jwalk = "0.8"
unicode-ident = "1.0"
toml = "0.7"
serde = { version = "1", features = ["derive"] }
colored = "2.0"
unicode-xid = "0.2.4"

[dev-dependencies]
pretty_assertions = "1.2"
expect-test = "1.4"
