[package]
name = "formatter"
version = "0.1.0"
edition = "2021"

[dependencies]
itertools = "0.11"
miette = { version = "5.9", features = ["fancy"] }
wca = { version = "0.1", git = "https://github.com/Wandalen/wTools.git", branch = "alpha" }
jwalk = "0.8"
unicode-ident = "1.0"

[dev-dependencies]
pretty_assertions = "1.2"
expect-test = "1.4"
